// Generated by CoffeeScript 1.6.2
$(function() {
  var elem, getQueryVariable, imageUrl;

  getQueryVariable = function(query) {
    var arg, argval, vars, _i, _len;

    vars = query.split("&");
    for (_i = 0, _len = vars.length; _i < _len; _i++) {
      arg = vars[_i];
      argval = arg.split("=");
      if (argval[0] === "imgurl") {
        return argval[1];
      }
    }
  };
  elem = $(".rg_di > a").first().attr("href");
  console.log(elem);
  imageUrl = getQueryVariable(elem);
  return window.location.replace(imageUrl);
});
