// Generated by CoffeeScript 1.6.2
var genericOnClick, id;

genericOnClick = function(info, tab) {
  console.log("info: " + (JSON.stringify(info)));
  return chrome.tabs.create({
    url: "search.html#" + info.srcUrl
  });
};

id = chrome.contextMenus.create({
  "title": "Search Same images on Google",
  "contexts": ["image"],
  "onclick": genericOnClick
});

console.log("context : " + id);

console.log("Hello World!");
